spring.application.name=fechafacil-backend
spring.datasource.url=jdbc:mysql://localhost:3306/fechafacil
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate